// <auto-generated />
using System;
using GTSmartBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GTSmartBank.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511011129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GTSmartBank.Models.ChiNhanh", b =>
                {
                    b.Property<int>("MaCN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCN"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCN");

                    b.ToTable("ChiNhanh");
                });

            modelBuilder.Entity("GTSmartBank.Models.GiaoDich", b =>
                {
                    b.Property<int>("MaGD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGD"));

                    b.Property<string>("LoaiGD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TK_Dich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TK_Nguon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianGD")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGD");

                    b.HasIndex("TK_Nguon");

                    b.ToTable("GiaoDich");
                });

            modelBuilder.Entity("GTSmartBank.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("GTSmartBank.Models.LichSuOTP", b =>
                {
                    b.Property<int>("MaOTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaOTP"));

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("MaGD")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThaiXacNhan")
                        .HasColumnType("bit");

                    b.HasKey("MaOTP");

                    b.HasIndex("MaGD");

                    b.ToTable("LichSuOTP");
                });

            modelBuilder.Entity("GTSmartBank.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaCN")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaCN");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("GTSmartBank.Models.SoTietKiem", b =>
                {
                    b.Property<string>("MaSo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KyHan")
                        .HasColumnType("int");

                    b.Property<decimal>("LaiSuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NgayDaoHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayMo")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoTienGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSo");

                    b.HasIndex("SoTaiKhoan");

                    b.ToTable("SoTietKiem");
                });

            modelBuilder.Entity("GTSmartBank.Models.TaiKhoan", b =>
                {
                    b.Property<string>("SoTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoaiTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCN")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMoTK")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoDu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("SoTaiKhoan");

                    b.HasIndex("MaCN");

                    b.HasIndex("MaKH");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("GTSmartBank.Models.GiaoDich", b =>
                {
                    b.HasOne("GTSmartBank.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TK_Nguon");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("GTSmartBank.Models.LichSuOTP", b =>
                {
                    b.HasOne("GTSmartBank.Models.GiaoDich", "GiaoDich")
                        .WithMany()
                        .HasForeignKey("MaGD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoDich");
                });

            modelBuilder.Entity("GTSmartBank.Models.NhanVien", b =>
                {
                    b.HasOne("GTSmartBank.Models.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaCN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");
                });

            modelBuilder.Entity("GTSmartBank.Models.SoTietKiem", b =>
                {
                    b.HasOne("GTSmartBank.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("SoTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("GTSmartBank.Models.TaiKhoan", b =>
                {
                    b.HasOne("GTSmartBank.Models.ChiNhanh", "ChiNhanh")
                        .WithMany()
                        .HasForeignKey("MaCN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GTSmartBank.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiNhanh");

                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
